"""Add percent_grade column to grades table

Revision ID: 25ea51b96421
Revises: 
Create Date: 2023-03-18 18:52:17.038930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ea51b96421'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percent_grade', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('letter_grade', sa.String(length=5), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_column('letter_grade')
        batch_op.drop_column('percent_grade')

    # ### end Alembic commands ###
