"""Delete score column from grades table

Revision ID: 43398a8282ff
Revises: 25ea51b96421
Create Date: 2023-03-18 19:28:32.968066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43398a8282ff'
down_revision = '25ea51b96421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
